[build]
  command = "npm run build"
  publish = "dist" 

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

/protected/*
  Basic-Auth: USERNAME:USER_PASSWORD SECOND_USERNAME:SECOND_USER_PASSWORD

